#=> Create a file based protection job for all linux sources
---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: 10.22.149.28
          cohesity_admin: "{{ username }}"
          cohesity_password: "{{ password }}"
          cohesity_validate_certs: False
          cohesity_protection:
              state: present
              job_name: "protect_vm"
              storage_domain: "DefaultStorageDomain"
              sources:
                - endpoint: "{{ item }}"
                  paths:
                    - includeFilePath: "/path1/"
                      excludeFilePaths:
                        - "/path1/exclude_path1" # This path should be present under /path1
                        - "/path1/exclude_path2" # This path should be present under /path1
                      skipNestedVolumes: False
                    - includeFilePath: "/path2"
                      excludeFilePaths:
                        - "/path2/exclude_path1" # This path should be present under /path2
                      skipNestedVolumes: False
              environment: "PhysicalFiles"
        with_items: "{{ groups['linux'] }}"
