---
- name: "Cohesity Virtual edition cluster: Set {{ cluster_name }} to state of {{ state | default('present') }}"
  cohesity_virtual_cluster:
    cluster: "{{ cohesity_server }}"
    username: "{{ cohesity_admin }}"
    password: "{{ cohesity_password }}"
    validate_certs: "{{ cohesity_validate_certs | default(False) }}"
    state: "{{ state | default('present') }}"
    cluster_name: "{{ cluster_name }}"
    metadata_fault_tolerance: "{{ metadata_fault_tolerance | default(0) }}"
    enable_encryption: "{{ enable_encryption | default(True) }}"
    enable_fips_mode: "{{ enable_fips_mode | default(True) }}"
    encryption_keys_rotation_period: "{{ encryption_keys_rotation_period | default(1) }}"
    cluster_gateway: "{{ cluster_gateway }}"
    cluster_subnet_mask: "{{ cluster_subnet_mask }}"
    domain_names: "{{ domain_names }}"
    ntp_servers: "{{ ntp_servers }}"
    dns_servers: "{{ dns_servers }}"
    virtual_ips: "{{ virtual_ips }}"
    virtual_ip_hostname: "{{ virtual_ip_hostname }}"
    nodes_ip: "{{ nodes_ip }}"
    wait: "{{ wait | default(True) }}"
    wait_minutes: "{{ wait_minutes | default(120) }}"
  tags: always
