# => Cohesity Agent Management
# =>
# => Role: cohesity.cohesity_ansible_role
# =>

# => Install the Cohesity Agent on each Linux host
# => specified in the Ansible inventory
# =>
---
  - hosts: linux
    # => We need to specify these variables to connect
    # => to the Cohesity cluster
    vars:
        var_cohesity_server: cluster_vip
        var_cohesity_admin: admin
        var_cohesity_password: admin
        var_validate_certs: False
    # => We need to gather facts to determine the OS type of
    # => the machine
    gather_facts: yes
    become: true
    collections:
        - cohesity.cohesity_collection
    tasks:
      - name: Remove Cohesity Agent from each Linux Server
        include_role:
            name: cohesity_ansible_role
            tasks_from: agent
        vars:
            cohesity_server: "{{ var_cohesity_server }}"
            cohesity_admin: "{{ var_cohesity_admin }}"
            cohesity_password: "{{ var_cohesity_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_agent:
                state: present
                # native_package: True
              
      #- name: Install new Cohesity Agent on each Linux Server
      #  include_role:
      #      name: cohesity.cohesity_ansible_role
      #      tasks_from: agent
      #  vars:
      #      cohesity_server: "{{ var_cohesity_server }}"
      #      cohesity_admin: "{{ var_cohesity_admin }}"
      #      cohesity_password: "{{ var_cohesity_password }}"
      #      cohesity_validate_certs: "{{ var_validate_certs }}"
      #      cohesity_agent:
      #          state: present
