# Playbook to delete protection policy.
---
  - hosts: localhost
    # => We need to specify these variables to connect
    # => to the Cohesity cluster
    vars:
      cohesity_server: cluster_vip
      cohesity_admin: admin
      cohesity_password: admin
      cohesity_validate_certs: False
    become: false
    collections:
        - cohesity.cohesity_collection
    tasks:
      - name: Delete protection policy from cohesity server.
        cohesity_policy:
            server: "{{ cohesity_server }}"
            admin: "{{ cohesity_admin }}"
            password: "{{ cohesity_password }}"
            validate_certs: "{{ cohesity_validate_certs }}"
            name: 'Ansible'
            state: 'absent'
