---
  - hosts: localhost
    # => We need to specify these variables to connect
    # => to the Cohesity cluster
    vars:
        var_cohesity_server: cluster_vip
        var_cohesity_admin: admin
        var_cohesity_password: admin
        var_validate_certs: False
    # => We need to gather facts to determine the OS type of
    # => the machine
    gather_facts: yes
    become: true
    collections:
        - cohesity.cohesity_collection
    tasks:
      - name: Add protection policy to cohesity server.
        include_role:
            name: cohesity_ansible_role
            tasks_from: policy
        vars:
            cohesity_server: "{{ var_cohesity_server }}"
            cohesity_admin: "{{ var_cohesity_admin }}"
            cohesity_password: "{{ var_cohesity_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_policy:
                name: 'Ansible'
                state: 'present'
                incremental_backup_schedule:
                   periodicity: Daily
