# Playbook to register Vmware source to the cluster.
---
- hosts: localhost
  # => We need to specify these variables to connect
  # => to the Cohesity cluster
  vars:
    cohesity_server: cluster_vip
    cohesity_admin: admin
    cohesity_password: admin
    cohesity_validate_certs: false
  become: false
  collections:
    - cohesity.cohesity_collection
  tasks:
    - name: "Cohesity Protection Source: Set Source to state of present }}"
      cohesity_source:
        server: "{{ cohesity_server }}"
        admin: "{{ cohesity_admin }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: present
        endpoint: "vcenter.domain.com"
        environment: "VMware"
        vmware_type: "VCenter"
        source_username: "admin"
        source_password: "admin"
