# => Collection: cohesity.cohesity_collection
# =>
#=> Start a protection job run.
---
  - hosts: workstation
    gather_facts: no
    collections:
      - cohesity.cohesity_collection
    vars:
      cohesity_server: cluster_vip
      cohesity_admin: admin
      cohesity_password: admin
      cohesity_validate_certs: false
    tasks:
      - name: Start Protection job
        cohesity_job:
          cluster: "{{ cohesity_server }}"
          username: "{{ cohesity_admin }}"
          password: "{{ cohesity_password }}"
          validate_certs: "{{ cohesity_validate_certs }}"
          state: "started"
          name: "DemoJob"
          environment: "VMware"
