#=> Remove Oracle protection job available in the vCenter
---
  - hosts: localhost
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: oracle_job
        vars:
          cohesity_server: orcl-serv2-eng-db.com
          cohesity_admin: "{{ username }}"
          cohesity_password: "{{ password }}"
          cohesity_validate_certs: False
          cohesity_oracle:
              state: present
              job_name: protect_oracle
