#=> Remove Oracle protection job available in the vCenter
---
  - hosts: localhost
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: oracle_job
        vars:
          cohesity_server: "{{ var_cohesity_server }}"
          cohesity_admin: "{{ var_cohesity_username }}"
          cohesity_password: "{{ var_cohesity_password }}"
          cohesity_validate_certs: "{{ var_validate_certs }}"
          cohesity_oracle:
              state: present
              job_name: protect_oracle
              storage_domain: "DefaultStorageDomain"
              policy: "Silver"
              endpoint: "{{ item }}"
              cancel_active: true
              environment: Oracle
              databases:
                - "dbs01"
              time_zone: Africa/Cairo
        with_items: "{{ groups['oracle'] }}"
